version: "3.6"
services:
  nginx:
    volumes:
    - app-data:/var/www
  php:
    volumes:
    - app-data:/var/www

volumes:
  app-data:
    driver: local
    driver_opts:
      type: nfs
      o: rw,async,noatime,rsize=32768,wsize=32768,proto=tcp,nfsvers=3,addr=host.docker.internal
      device: ":${APP_PATH}"